const CertificateModel = [
    "certificate_name", 
    "certificate_status", 
    "certificate_link", 
    "update_status_date", 
    "previous_update_status_date", 
    "previous_status", 
    "date", 
    "endDate", 
    "blankNumber", 
    "technicalReglaments", 
    "group", 
    "certType", 
    "certObjectType", 
    "applicantLegalSubjectType", 
    "applicantType", 
    "applicantName", 
    "applicantOpf", 
    "applicantFilialFullNames", 
    "manufacterLegalSubjectType", 
    "manufacterType", 
    "manufacterName", 
    "manufacterOpf", 
    "manufacterFilialFullNames", 
    "idRalCertificationAuthority", 
    "certificationAuthorityAttestatRegNumber", 
    "productOrig", 
    "productFullName", 
    "productBatchSize", 
    "productIdentificationName", 
    "productIdentificationType", 
    "productIdentificationTrademark", 
    "productIdentificationModel", 
    "productIdentificationArticle", 
    "productIdentificationSort", 
    "productIdentificationGtin", 
    "expertFio", 
    "expertSnils", 
    "id", 
    "certificate_id",
    "certificate_testinglabs__id", //внешняя
    "certification_authority__id", //внешняя
    "certificate_applicant__id", //внешняя
] as const;

export type TCertificateModel = typeof CertificateModel[number];