const CertificateModel = [
    "certificate_name", 
    "certificate_status", 
    "certificate_link", 
    "update_status_date", 
    "previous_update_status_date", 
    "previous_status", 
    "date", 
    "endDate", 
    "blankNumber", 
    "technicalReglaments", 
    "group", 
    "certType", 
    "certObjectType", 
    "applicantLegalSubjectType", 
    "applicantType", 
    "applicantName", 
    "applicantOpf", 
    "applicantFilialFullNames", 
    "manufacterLegalSubjectType", 
    "manufacterType", 
    "manufacterName", 
    "manufacterOpf", 
    "manufacterFilialFullNames", 
    "idRalCertificationAuthority", 
    "certificationAuthorityAttestatRegNumber", 
    "productOrig", 
    "productFullName", 
    "productBatchSize", 
    "productIdentificationName", 
    "productIdentificationType", 
    "productIdentificationTrademark", 
    "productIdentificationModel", 
    "productIdentificationArticle", 
    "productIdentificationSort", 
    "productIdentificationGtin", 
    "expertFio", 
    "expertSnils", 
    "id", 
    "certificate_id",


    'link',
    'nameType',
    'nameTypeActivity',
    'fullName',
    'address',
    'oaDescription',
    'NPstatus',
    'ral_short_info_view__id',
    'regDate',
    'NP_status_change_date',
    'applicantFullName',
    'old_status_AL',
    'new_status_AL',
    'applicantINN',
    'applicantINN',
    'RegNumber',
    'status_change_date',
    'regulations',
    'tnved',
    'regulation',


] as const;

export type TCertificateModel = typeof CertificateModel[number];