const CertificateModel = [
    // Основные поля сертификата
    "certificate_name",
    "certificate_status",
    "id",
    "certificate_id",
    "certificate_link",
    "update_status_date",
    "previous_update_status_date",
    "previous_status",
    "date",
    "endDate",
    "blankNumber",
    "technicalReglaments",
    "group",
    "certType",
    "certObjectType",
    
    // Информация о заявителе (applicant)
    "applicantLegalSubjectType",
    "applicantType",
    "applicantName",
    "applicantOpf",
    "applicantFilialFullNames",
    
    // Информация о производителе (manufacturer)
    "manufacterLegalSubjectType",
    "manufacterType",
    "manufacterName",
    "manufacterOpf",
    "manufacterFilialFullNames",
    
    // Продукция
    "idRalCertificationAuthority",
    "certificationAuthorityAttestatRegNumber",
    "productOrig",
    "productFullName",
    "productBatchSize",
    "productIdentificationName",
    "productIdentificationType",
    "productIdentificationTrademark",
    "productIdentificationModel",
    "productIdentificationArticle",
    "productIdentificationSort",
    "productIdentificationGtin",
    
    // Эксперты
    "expertFio",
    "expertSnils",
    
    // Поля из ral_short_info_view (с префиксами)
    "ral_short_info_view__link",
    "ral_short_info_view__RegNumber",
    "ral_short_info_view__old_status_AL",
    "ral_short_info_view__new_status_AL",
    "ral_short_info_view__status_change_date",
    "ral_short_info_view__nameType",
    "ral_short_info_view__nameTypeActivity",
    "ral_short_info_view__regDate",
    "ral_short_info_view__fullName",
    "ral_short_info_view__address",
    "ral_short_info_view__applicantINN",
    "ral_short_info_view__applicantFullName",
    "ral_short_info_view__oaDescription",
    "ral_short_info_view__id",
    "ral_short_info_view__NPstatus",
    "ral_short_info_view__NP_status_change_date",
    "ral_short_info_view__regulations",
    
    // Поля из certificate_applicant (с префиксами)
    "certificate_applicant__certificate_id",
    "certificate_applicant__idLegalSubject",
    "certificate_applicant__idEgrul",
    "certificate_applicant__idApplicantType",
    "certificate_applicant__idLegalSubjectType",
    "certificate_applicant__fullName",
    "certificate_applicant__shortName",
    "certificate_applicant__idPerson",
    "certificate_applicant__surname",
    "certificate_applicant__firstName",
    "certificate_applicant__patronymic",
    "certificate_applicant__headPosition",
    "certificate_applicant__ogrn",
    "certificate_applicant__ogrnAssignDate",
    "certificate_applicant__inn",
    "certificate_applicant__kpp",
    "certificate_applicant__idLegalForm",
    "certificate_applicant__regDate",
    "certificate_applicant__regOrganName",
    "certificate_applicant__addlRegInfo",
    "certificate_applicant__isEecRegister",
    "certificate_applicant__passportIssueDate",
    "certificate_applicant__passportIssuedBy",
    "certificate_applicant__passportNum",
    "certificate_applicant__idPersonDoc",
    "certificate_applicant__id",
    
    // Поля из certification_authority (с префиксами)
    "certification_authority__certificate_id",
    "certification_authority__idCertificationAuthority",
    "certification_authority__fullName",
    "certification_authority__accredOrgName",
    "certification_authority__attestatRegNumber",
    "certification_authority__attestatRegDate",
    "certification_authority__attestatEndDate",
    "certification_authority__idRal",
    "certification_authority__ogrn",
    "certification_authority__idPerson",
    "certification_authority__firstName",
    "certification_authority__surname",
    "certification_authority__patronymic",
    "certification_authority__id",
    
    // Поля из status_change (с префиксами)
    "status_change__certificate_id",
    "status_change__status",
    "status_change__begin_date",
    "status_change__end_date",
    "status_change__comment",
    "status_change__publish_date",
    "status_change__status_changes_by",
    "status_change__id",
    "status_change__idChangeStatus"
] as const;

export type TCertificateModel = typeof CertificateModel[number];